### ISSUE TITLE
why the implemented bilateral upsample returns a random affine transform

### ISSUE THREAD

**Issue by zhuyinheng** [harshsinh/deepbilateral#1]
https://github.com/harshsinh/deepbilateral/blob/f6a65e85774090b64185ccb086f4a5f3cf7f97d8/scripts/main.ipynb#L240-L249

It seems that the bilateral slicing operation is not implemented. Maybe you can refer to  torch.nn.functional.grid_sample for a plausible implementation.

**Comment by orrbarkat** [comment]
any news?

**Comment by deepakgangwar** [comment]
@cow8 @orrbarkat this was for testing purpose only. Implementation of bilateral slicing has been pushed also.
I am closing the issue now.
